# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb2b759f0175becb82afd41f2b3aa58c38dd360a26d8ba482a1487fa63a49fbd3b9a171a1306f850d48d8aee9c7cdae05453e5dd7197d041e174131161e8410

test:
  secret_key_base: cb6562aa5b31c4969a06d8a4ed248f825b20353c24991334f3ea40b4cf05e760b73d61dceae67a9a9f1026f9bcb885781c091bc1de495f08ee2f81d3ca32f182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
